'use strict';

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Methods', 'POST,OPTIONS');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
        
          if (req.method === 'OPTIONS') {
              return res.status(200).end();
                }
                
                  if (req.method !== 'POST') {
                      return res.status(405).json({ error: 'Method not allowed' });
                        }
                        
                          try {
                              const apiKey = process.env.ANTHROPIC_API_KEY;
                              
                                  if (!apiKey) {
                                        console.error('[assistant] missing ANTHROPIC_API_KEY');
                                              return res.status(500).json({ error: 'ANTHROPIC_API_KEY is not configured' });
                                                  }
                                                  
                                                      let body = req.body;
                                                      
                                                          if (typeof body === 'string') {
                                                                try {
                                                                        body = JSON.parse(body);
                                                                              } catch (e) {
                                                                                      console.error('[assistant] invalid JSON body:', body);
                                                                                              return res.status(400).json({ error: 'Invalid JSON body' });
                                                                                                    }
                                                                                                        }
                                                                                                        
                                                                                                            body = body || {};
                                                                                                            
                                                                                                                const message = String(body.message || body.text || body.prompt || '').trim();
                                                                                                                    const context = String(body.context || '').trim();
                                                                                                                    
                                                                                                                        if (!message) {
                                                                                                                              console.error('[assistant] empty message body:', body);
                                                                                                                                    return res.status(400).json({ error: 'message is required' });
                                                                                                                                        }
                                                                                                                                        
                                                                                                                                            const userText = context
                                                                                                                                                  ? `السياق:\n${context}\n\nالسؤال:\n${message}`
                                                                                                                                                        : message;
                                                                                                                                                        
                                                                                                                                                            const payload = {
                                                                                                                                                                  model: 'claude-3-haiku-20240307',
                                                                                                                                                                        max_tokens: 700,
                                                                                                                                                                              temperature: 0.4,
                                                                                                                                                                                    messages: [
                                                                                                                                                                                            {
                                                                                                                                                                                                      role: 'user',
                                                                                                                                                                                                                content: userText
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                      console.log('[assistant] sending request to anthropic with payload:', JSON.stringify(payload));
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          const upstream = await fetch('https://api.anthropic.com/v1/messages', {
                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                      headers: {
                                                                                                                                                                                                                                                              'content-type': 'application/json',
                                                                                                                                                                                                                                                                      'x-api-key': apiKey,
                                                                                                                                                                                                                                                                              'anthropic-version': '2023-06-01'
                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                          body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                  const raw = await upstream.text();
                                                                                                                                                                                                                                                                                                      console.log('[assistant] anthropic status:', upstream.status);
                                                                                                                                                                                                                                                                                                          console.log('[assistant] anthropic raw response:', raw);
                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                              let data = {};
                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                        data = raw ? JSON.parse(raw) : {};
                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                  console.error('[assistant] failed to parse anthropic json:', e.message);
                                                                                                                                                                                                                                                                                                                                        return res.status(502).json({
                                                                                                                                                                                                                                                                                                                                                error: 'Anthropic returned non-JSON response',
                                                                                                                                                                                                                                                                                                                                                        raw
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                      if (!upstream.ok) {
                                                                                                                                                                                                                                                                                                                                                                            return res.status(upstream.status).json({
                                                                                                                                                                                                                                                                                                                                                                                    error: data?.error?.message || data?.message || 'Anthropic request failed',
                                                                                                                                                                                                                                                                                                                                                                                            details: data
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                          const responseText = Array.isArray(data?.content)
                                                                                                                                                                                                                                                                                                                                                                                                                ? data.content.map((x) => x?.text).filter(Boolean).join('\n').trim()
                                                                                                                                                                                                                                                                                                                                                                                                                      : '';
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                response: responseText || 'لم يتم إنشاء رد.'
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error('[assistant] unexpected error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                    error: err?.message || 'Internal server error'
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          };'