'use strict';

const https = require('https');

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST,OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

        if (req.method === 'OPTIONS') {
            return res.status(200).end();
              }

                if (req.method !== 'POST') {
                    return res.status(405).json({ error: 'Method not allowed' });
                      }

                        try {
                            const apiKey = process.env.ANTHROPIC_API_KEY;
                                if (!apiKey) {
                                      return res.status(500).json({ error: 'ANTHROPIC_API_KEY missing' });
                                          }

                                              let body = req.body;

                                                  if (typeof body === 'string') {
                                                        try {
                                                                body = JSON.parse(body);
                                                                      } catch (e) {
                                                                              return res.status(400).json({ error: 'Invalid JSON body', rawBody: body });
                                                                                    }
                                                                                        }

                                                                                            body = body || {};

                                                                                                const message = String(body.message || '').trim();
                                                                                                    const context = String(body.context || '').trim();

                                                                                                        if (!message) {
                                                                                                              return res.status(400).json({ error: 'message required', body });
                                                                                                                  }

                                                                                                                      const prompt = context
                                                                                                                            ? `السياق:\n${context}\n\nالسؤال:\n${message}`
                                                                                                                                  : message;

                                                                                                                                      const payloadObject = {
                                                                                                                                            model: 'claude-3-haiku-20240307',
                                                                                                                                                  max_tokens: 600,
                                                                                                                                                        messages: [
                                                                                                                                                                {
                                                                                                                                                                          role: 'user',
                                                                                                                                                                                    content: prompt
                                                                                                                                                                                            }
                                                                                                                                                                                                  ]
                                                                                                                                                                                                      };

                                                                                                                                                                                                          const payload = JSON.stringify(payloadObject);

                                                                                                                                                                                                              const options = {
                                                                                                                                                                                                                    hostname: 'api.anthropic.com',
                                                                                                                                                                                                                          path: '/v1/messages',
                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                      headers: {
                                                                                                                                                                                                                                              'Content-Type': 'application/json',
                                                                                                                                                                                                                                                      'x-api-key': apiKey,
                                                                                                                                                                                                                                                              'anthropic-version': '2023-06-01',
                                                                                                                                                                                                                                                                      'Content-Length': Buffer.byteLength(payload)
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                    const upstreamBody = await new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                          const request = https.request(options, (response) => {
                                                                                                                                                                                                                                                                                                  let data = '';

                                                                                                                                                                                                                                                                                                          response.on('data', (chunk) => {
                                                                                                                                                                                                                                                                                                                    data += chunk;
                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                    response.on('end', () => {
                                                                                                                                                                                                                                                                                                                                              resolve({
                                                                                                                                                                                                                                                                                                                                                          statusCode: response.statusCode || 0,
                                                                                                                                                                                                                                                                                                                                                                      body: data
                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                    request.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                                                                          request.write(payload);
                                                                                                                                                                                                                                                                                                                                                                                                                request.end();
                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                        let parsed;
                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                  parsed = upstreamBody.body ? JSON.parse(upstreamBody.body) : {};
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(502).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                    error: 'Anthropic returned non-JSON',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            upstreamStatus: upstreamBody.statusCode,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raw: upstreamBody.body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (upstreamBody.statusCode >= 400) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(upstreamBody.statusCode).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error: parsed?.error?.message || parsed?.message || 'Anthropic request failed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        upstreamStatus: upstreamBody.statusCode,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                details: parsed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const responseText =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Array.isArray(parsed?.content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? parsed.content.map((x) => x?.text).filter(Boolean).join('\n').trim()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              response: responseText || 'لم يتم إنشاء رد.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    debug: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            upstreamStatus: upstreamBody.statusCode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  error: err?.message || 'Internal server error',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stack: err?.stack || null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };